<?php

namespace ContainerS2QeZrq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNavbarService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Components\Navbar' autowired service.
     *
     * @return \App\Components\Navbar
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Components/Navbar.php';

        $container->factories['service_container']['App\\Components\\Navbar'] = function () use ($container) {
            return new \App\Components\Navbar();
        };

        return $container->factories['service_container']['App\\Components\\Navbar']();
    }
}
