<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Patient extends \App\Entity\Patient implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'surname', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'fiscal_code', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'phone_number', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'birth_date', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'birth_place', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'gender', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'city_of_residence', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'street', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'medicalExaminations'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'surname', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'fiscal_code', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'phone_number', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'birth_date', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'birth_place', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'gender', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'city_of_residence', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'street', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'medicalExaminations'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Patient $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurname(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurname', []);

        return parent::getSurname();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurname(string $surname): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurname', [$surname]);

        return parent::setSurname($surname);
    }

    /**
     * {@inheritDoc}
     */
    public function getFiscalCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFiscalCode', []);

        return parent::getFiscalCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setFiscalCode(string $fiscal_code): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFiscalCode', [$fiscal_code]);

        return parent::setFiscalCode($fiscal_code);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneNumber(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneNumber', []);

        return parent::getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneNumber(?string $phone_number): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneNumber', [$phone_number]);

        return parent::setPhoneNumber($phone_number);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthDate', []);

        return parent::getBirthDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthDate(\DateTimeInterface $birth_date): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthDate', [$birth_date]);

        return parent::setBirthDate($birth_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthPlace(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthPlace', []);

        return parent::getBirthPlace();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthPlace(string $birth_place): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthPlace', [$birth_place]);

        return parent::setBirthPlace($birth_place);
    }

    /**
     * {@inheritDoc}
     */
    public function getGender(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', []);

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setGender(?string $gender): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', [$gender]);

        return parent::setGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function getCityOfResidence(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCityOfResidence', []);

        return parent::getCityOfResidence();
    }

    /**
     * {@inheritDoc}
     */
    public function setCityOfResidence(?string $city_of_residence): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCityOfResidence', [$city_of_residence]);

        return parent::setCityOfResidence($city_of_residence);
    }

    /**
     * {@inheritDoc}
     */
    public function getStreet(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStreet', []);

        return parent::getStreet();
    }

    /**
     * {@inheritDoc}
     */
    public function setStreet(?string $street): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStreet', [$street]);

        return parent::setStreet($street);
    }

    /**
     * {@inheritDoc}
     */
    public function getMedicalExaminations(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedicalExaminations', []);

        return parent::getMedicalExaminations();
    }

    /**
     * {@inheritDoc}
     */
    public function addMedicalExamination(\App\Entity\MedicalExamination $medicalExamination): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMedicalExamination', [$medicalExamination]);

        return parent::addMedicalExamination($medicalExamination);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMedicalExamination(\App\Entity\MedicalExamination $medicalExamination): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMedicalExamination', [$medicalExamination]);

        return parent::removeMedicalExamination($medicalExamination);
    }

}
