<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS2QeZrq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS2QeZrq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS2QeZrq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS2QeZrq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS2QeZrq\App_KernelDevDebugContainer([
    'container.build_hash' => 'S2QeZrq',
    'container.build_id' => 'd3d9ad4c',
    'container.build_time' => 1679855250,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS2QeZrq');
