<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'add_medical_examination' => [[], ['_controller' => 'App\\Controller\\MedicalExaminationController::medicalExamination'], [], [['text', '/add_medical_examination']], [], [], []],
    'medical_examination_list' => [[], ['_controller' => 'App\\Controller\\MedicalExaminationController::medicalExaminationList'], [], [['text', '/medical_examination_list']], [], [], []],
    'remove_medical_examination' => [[], ['_controller' => 'App\\Controller\\MedicalExaminationController::removeMedicalExamination'], [], [['text', '/remove_medical_examination']], [], [], []],
    'medical_examinations_patient' => [[], ['_controller' => 'App\\Controller\\MedicalExaminationController::medicalExaminationPatientList'], [], [['text', '/medical_examinations_patient']], [], [], []],
    'mod_medical_examination' => [[], ['_controller' => 'App\\Controller\\MedicalExaminationController::modMedicalExamination'], [], [['text', '/mod_medical_examination']], [], [], []],
    'modify_medical_examination' => [[], ['_controller' => 'App\\Controller\\MedicalExaminationController::modifyMedicalExamination'], [], [['text', '/modify_medical_examination']], [], [], []],
    'add_patient' => [[], ['_controller' => 'App\\Controller\\PatientController::addPatient'], [], [['text', '/add_patient']], [], [], []],
    'patients_list' => [[], ['_controller' => 'App\\Controller\\PatientController::patientsList'], [], [['text', '/patients_list']], [], [], []],
    'remove_patient' => [[], ['_controller' => 'App\\Controller\\PatientController::removePatient'], [], [['text', '/remove_patient']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\WebController::index'], [], [['text', '/']], [], [], []],
    'insert_medical_examination' => [[], ['_controller' => 'App\\Controller\\WebController::insertMedicalExamination'], [], [['text', '/insert_medical_examination']], [], [], []],
    'insert_patient' => [[], ['_controller' => 'App\\Controller\\WebController::insertPatient'], [], [['text', '/insert_patient']], [], [], []],
];
